version: "3.7"
services:
  techno:
    image: node:19-alpine3.16
    container_name: techno
    ports:
      - 3000:3000
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
    command: tail -f /dev/null
